credentials:
  usernames:
    deofis:
      email: deofis2015@gmail.com
      logged_in: False # Will be managed automatically
      name: Efosa Dave Omosigho
      password: 'abc123' # Will be hashed automatically
cookie:
  expiry_days: 30
  key: cookie_signature_key # Must be string
  name: cookie_name
preauthorized:
  emails:
  - efosa.dave@azubiafrica.org
users: